site_name: Subkube Docs
theme:
  name: material
  logo: img/logo.png
  features:
    - navigation.tabs
  palette:
    primary: white
  font:
    text: Source Sans Pro

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist
  - attr_list

google_analytics:
  - G-D0ZB95JSN5
  - auto

nav:
  - Home: index.md
  - Getting Started:
    - Getting Started: getting_started.md
  - Concepts:
    - Project: concepts/project.md
    - Workloads: concepts/workloads.md
    - Security: concepts/security.md
  - Guides:
    - Deploy from Docker Compose using Kompose: guides/kompose.md
    - Deploy using Helm: guides/helm.md
    - Configure a Pod to run with a limited SecurityContext: guides/pod-security-context.md
    - Using Ingress with CertManager: guides/ingress-certmanager.md
    - Using Ingress with a Wildcard domain & certificate: guides/soon.md
    - Automated Deployment using Github Actions: guides/deploy-github-actions.md
  - CLI:
    - subctl: cli.md
  - API:
    - Authentication: api/authentication.md
    - Reference: soon.md

extra_css:
  - stylesheets/extra.css
