site_name: SubKube Developers
theme:
  name: material
  logo: img/logo.png
  features:
    - navigation.tabs
  palette:
    primary: white
  font:
    text: Source Sans Pro

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
    - Getting Started: getting_started.md
  - Concepts:
    - Workloads: concepts/workloads.md
    - Project: concepts/project.md
  - Guides:
    - Using Ingress with CertManager on SubKube: soon.md
    - Volumes on SubKube: soon.md
  - CLI:
    - subctl: cli.md
  - API:
    - Authentication: api/authentication.md
    - Reference: soon.md
